- index.html
- public/js/client.js
- public/js/game.js
resolves #4 
Resolvendo essa issue aprendi três coisas
- **sintaxe de módulos do ES6 + node:** node ainda não tem suporte completo a sintaxe de módulos do ES6, só em [branches experimentais](https://stackoverflow.com/questions/45854169/how-can-i-use-an-es6-import-in-node), o padrão node é CommonJS (acho que eu ja tinha visto isso mas não lembrava, afinal imports e módulos no javascript é um crazy hell, mas foi legal tentar usar `export default` no node, ver dar errado e re-lembrar o porque).
- **cliente é cliente, server é server:** ao implementar o Client em um arquivo separado, tentei exportar a classe como um módulo e usar require (CommonJs) no arquivo do Game (já que minhas tentativas de usar `import` tinham falhado), mas recebi um erro "require is not defined", isso é porque o …
> Organize client code

- public/js/client.js
Everybody deserves move using WASD too. ;)
> Add WASD input commands

- README.md
Update readme with deno installation instructions link .
> Update Deno installation info

- client/js/client.js
- client/js/game.js
- server/clientHandler.ts
When the player logs in, it applies any server rules to the visible game
You can test this PR [here](https://diguifi-tests-tiny-mmo.herokuapp.com/)
> Applies server configs at login

- client/js/client.js
- server/clientHandler.ts
Resolves #15 
You can test this PR [here](https://diguifi-tests-tiny-mmo.herokuapp.com/)
> Broadcasts only which player moved

- client/js/client.js
- client/js/game.js
- server/clientHandler.ts
- player class on client
- smaller ping event and longer timeout
- use variable `players` on game obj instead of clients obj (since players are entities of the game, like the board, the client only updates it)
- little smaller login obj from server
> Creates player class on client

- client/js/client.js
> Remove vars from project

- client/index.html
- client/js/client.js
- client/js/game.js
- client/js/main.js
- server.ts
- server/clientHandler.ts
- server/player.ts
This adds a really cool feature: allow the player to draw himself.
**Important** - this PR adds 155 bytes to each player data. But this is only transferred when a player logs in (before and after):
> Add player made shape

- client/index.html
- Add title and subtitle
- Adds some required meta tags
- Improves the look of the login screen
- Adds a new font that matches the game style
**Old:**
**New:**
> Improves the login screen

- client/js/client.js
- client/js/game.js
Now all messages received from the server have a central parsing point, with a respective object as result for the parsed values
> Add client parser

- client/index.html
- client/js/Enums.js
- client/js/Main.js
- client/js/entities/Player.js
- client/js/parser/ParseError.js
- client/js/parser/Parser.js
- server.ts
- server/Enums.ts
- server/clientHandler.ts
Resolves #45 
Resolves #47 
- Fixes error when walking towards the map limit
- Blocks login button after first successful click to avoid spam
- Creates case of "Error" when a duplicated name tries to log in
> Some bugfixes

- client/js/Client.js
- client/js/Enums.js
- client/js/Game.js
- client/js/board/map/InitialRoom.js
- client/js/board/map/Map.js
- client/js/board/map/Woods.js
- client/js/entities/Player.js
- client/js/parser/Parser.js
- server/Enums.ts
- server/clientHandler.ts
- server/map/map.ts
- server/map/rooms/exits.ts
- server/map/rooms/initialRoom.ts
- server/map/rooms/room.ts
- server/map/rooms/woods.ts
- server/player.ts
> Rooms fixes

- client/index.html
- client/js/Client.js
- client/js/Game.js
- client/js/Main.js
- client/js/drawingCanvas/DrawingCanvas.js
I always feel the need to show this project to my friends, but it has absolutely no mobile support, so I always need a computer nearby...
This PR adds basic mobile support (player drawing and movimentation).
> Extremely basic mobile support

- client/index.html
- client/js/Client.js
- client/js/Main.js
- client/js/board/map/tiles/Color.js
Resolve #55 
Also made some adjustments to the mobile version
> Fixed color palette for players

- server.ts
> Automatically serves entire client folder

- client/js/Client.js
- server/player.ts
> Adds delay to player movement

- client/index.html
- client/js/Client.js
- client/js/Enums.js
- client/js/board/layers/SpritesLayer.js
- client/js/entities/Npc.js
- client/js/entities/Npcs.js
- client/js/parser/ParseNpcMove.js
- client/js/parser/ParseNpcsInRoom.js
- client/js/parser/Parser.js
- server/Enums.ts
- server/clientHandler.ts
- server/entities/dog.ts
- server/entities/npc.ts
- server/entities/player.ts
- server/map/map.ts
- server/map/rooms/initialRoom.ts
- server/map/rooms/room.ts
- server/map/rooms/woods.ts
Resolve #58 
Features:
- NPCs for each room of the game
- NPCs random movement
- NPC moves are broadcasted only on its room
- Only players switching rooms receive the list of NPCs on the new room (unicast)
- No collision or interaction yet
> First passive NPC mechanics

- server/clientHandler.ts
- server/entities/npc.ts
- server/entities/player.ts
Resolves first task of #63 
(server side only)
> NPC collision

- server/entities/npc.ts
Uses math to check player inside circle:
> Way better logic for following behaviour

- Procfile
- README.md
- server/clientHandler.ts
- server/db/main.ts
> Merge with Master

- server/entities/items/itemBase.ts
- server/entities/npc.ts
- server/entities/npcs/quests/humans/helpTheLakeVillage.ts
- server/entities/npcs/quests/quest.ts
- server/entities/npcs/quests/step.ts
- server/entities/player.ts
- server/map/rooms/room.ts
> Item despawn and some fixes

- server/entities/player.ts
> Fixes afk method
